### ISSUE TITLE
Setting for Minimap appearance

### ISSUE THREAD

**Issue by notIkibo** [VoxelMap2/VoxelMap#14]
Heyaaa maintainer :3

This mod is so useful and I am thankful for your existance, but I do have a thing to point out.
It's a small thing, but also feels unpolished.

If you have time and motivation, maybe you could either add a setting or make it a standard that the minimap doesn't show (or loses opacity) when either escaping or being in inventory. For those who either have roughly enough items or blur (this little mod that blurs the background when escaping or being in inventory), it is kinda being in the way.

Maybe you only maintain and fix bugs, I don't know your philosophy on that one, but a response would be nice. Even if it's a clear no. 

Ikibo

**Comment by TheAlgorithm476** [comment]
Hello, we _mostly_ focus on maintaining and fixing bugs, but we have been, and probably will continue to do so for the foreseeable future, allowing feature requests to be made. I have added your suggestion to the list of ideas.

This is not a promise of it actually happening, but if we ever have the time to do it, and it is fitting to do it at that time, your suggestion will be revisited, and acted upon.

Thanks for the suggestion! You can track the status of your idea on our Trello board.

**Comment by notIkibo** [comment]
That's totally cool, alrighty then. I'll be waiting patiently and try to find your Trello Board :3
