### ISSUE TITLE
An issue with the map menu, incompatibility with Things mod

### ISSUE THREAD

**Issue by GDHJDSYDH** [VoxelMap2/VoxelMap#15]
When I press the key button and open the map menu, it shows no map. The place where the map is originally displayed is pitch black. If I set waypoints, it only displays the name of the waypoints in this black place. However, the minimap is working fine. And I don't know where the issue is. 

[Update] After investigation, I found that after removing the "Things" mod, the issue is solved.

**Comment by TheAlgorithm476** [comment]
The map going black is an issue we've heard in the past, and the terrible structure and optimization of the map is to blame for this. Restarting the game usually fixes it. We are working on a recode of the map, but it's taking some time to do.
