### ISSUE TITLE
'Right Click for More'  in Crafting Book stops working with VoxelMap installed

### ISSUE THREAD

**Issue by Sylxeria** [VoxelMap2/VoxelMap#18]
Latest version (1.20.1-1.12.13)  of Voxel Map,  no other mods installed.

When in the Crafting interface, if in the Recipe Book you have multiple options available  (Example  -  Oak Boat, Jungle Boat, Birch Boat)  when  VoxelMap is enabled it prevents the use of the right-click context for pulling up additional crafting options.

**Comment by fantahund** [comment]
Fixed in 1.20 Version

**Comment by fantahund** [comment]
Fixed in 1.20 Version
