### ISSUE TITLE
[1.19.4] Incorrect rendering of marker layers 

### ISSUE THREAD

**Issue by Galy4a** [VoxelMap2/VoxelMap#2]
The map marker layer is drawn under the rest of the environment
![2023-03-18_11 15 05](https://user-images.githubusercontent.com/14756365/226084617-b529335a-80e7-405a-a86b-a270af3a818a.png)
![2023-03-18_11 23 15](https://user-images.githubusercontent.com/14756365/226084620-52ee95f9-a8e9-4fb8-a051-492b32e77924.png)

**Comment by fantahund** [comment]
Fixed ~https://modrinth.com/mod/voxelmap-updated/version/1.19.4-1.12.3
