### ISSUE TITLE
Unknown or incomplete command, when using Teleport to

### ISSUE THREAD

**Issue by MaoYan5985** [VoxelMap2/VoxelMap#3]
![ZK99`G0}GD7U~$)SSQ8S9~G](https://user-images.githubusercontent.com/122714639/230606935-d0473807-3198-46cd-8d11-0164daa1a124.png)
When I use the teleport on my server, the chat always shows this message. I know the mod runs both /tp and /tppos commands when teleporting, but it's annoying to get errors every time when teleporting in the server that doesn't support /tppos.
I was wondering if it is possible to change the command used for teleporting through the settings?

**Comment by TheAlgorithm476** [comment]
Hello MaoYan5985

The tppos command has recently been removed from VoxelMap. The command got removed in the following versions:
- 1.12.3_2 for 1.19.4
- 1.12.3 for 23w14a

Updating to any of these versions will not show the error again.
