### ISSUE TITLE
1.20 CAN NOT set SEED in SERVER

### ISSUE THREAD

**Issue by ghitori** [VoxelMap2/VoxelMap#7]
The box of seed can only input seed, and then nothing happened.

Input SEED,
![image](https://github.com/Updated-VoxelMap/VoxelMap/assets/29966961/e3c4f29e-c035-42d5-b7bb-1b1f1d7d93ae),
and then press Enter
![image](https://github.com/Updated-VoxelMap/VoxelMap/assets/29966961/559375c2-82ef-4d87-9a3c-6869df77e07a)

**Comment by Dunmeritude** [comment]
Also having this issue. When entering a seed on a multiplayer server, it reverts to "unknown" on pressing enter. The server is Fabric, if that may have anything to do with it.
