### ISSUE TITLE
Translations are not applied in the interface

### ISSUE THREAD

**Issue by Galy4a** [VoxelMap2/VoxelMap#8]
Hello, I noticed that only those words that are found in the general translation of the game are translated in the interface, the rest of the words remain without translation.
I added translations to the missing words for my language, but unfortunately due to problems with translations, I could not check the display in the interface.
[ru_ru.json](https://github.com/Galy4a/VoxelMap/blob/voxelmax.lang-ru/src/ru_ru.json)

**Comment by fantahund** [comment]
It's in the version on my Jenkins now. On Modrinth I will publish it with the next version
https://jenkins.fantacs.de/job/VoxelMap/
